name: terraform-plan-comment-action
description: Creates a comment with all changes from `terraform plan`.
author: DREST LTD
inputs:
  token:
    description: GitHub token. Defaults to secrets.GITHUB_TOKEN.
    required: false
    default: ${{ github.token }}
  name:
    description: The name of the artifact containing the output of `terraform plan`.
    required: false
    default: terraform-plan
  path:
    description: A path glob to check for `terraform plan` output files.
    required: false
  plan:
    description: The output of `terraform plan`.
    required: false
  header:
    description: Header for comment message
    required: false
    default: 'Terraform infrastructure changes'
outputs:
  terraform-changes:
    description: returns true if there are changes in terraform, else false
runs:
  using: 'node12'
  main: 'dist/index.js'
